apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: ping-app
spec:
  provider:
    vault:
      server: "https://vault-cluster-public-vault-aa97d3d4.2f79cd88.z1.hashicorp.cloud:8200"
      path: "ping-app"
      version: "v2"
      namespace: "admin"
      auth:
        jwt:
          # Path where the JWT authentication backend is mounted - /auth/ is added, dont use it here.
          path: "jwt-ping"
          role: "ping-app"
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: "vault-auth"
            audiences:
            - "https://kubernetes.default.svc"
            expirationSeconds: 3600